"""add_length_mm_to_distinta_items

Revision ID: 2a43f95d17df
Revises: 98a6eaedc630
Create Date: 2026-05-24 14:09:35.382279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a43f95d17df'
down_revision: Union[str, Sequence[str], None] = '98a6eaedc630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distinta_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('length_mm', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distinta_items', schema=None) as batch_op:
        batch_op.drop_column('length_mm')

    # ### end Alembic commands ###
