"""add_cutting_plans_stock_reservations_material_fields

Revision ID: 76d3be77f4e5
Revises: 2a43f95d17df
Create Date: 2026-05-24 15:05:33.635775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76d3be77f4e5'
down_revision: Union[str, Sequence[str], None] = '2a43f95d17df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cutting_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commessa_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('pezzi_ricavati', sa.Text(), nullable=True),
    sa.Column('sfrido_dim1', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sfrido_dim2', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sfrido_percentuale', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['commessa_id'], ['commesse.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cutting_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cutting_plans_commessa_id'), ['commessa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cutting_plans_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cutting_plans_material_id'), ['material_id'], unique=False)

    op.create_table('stock_reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('commessa_id', sa.Integer(), nullable=False),
    sa.Column('tipo_movimento', sa.Enum('PRENOTAZIONE', 'CONFERMA_USCITA', 'RIENTRO_SFRIDO', name='tipomovimentoriserva'), nullable=False),
    sa.Column('quantita', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('dimensione_1', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('dimensione_2', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['commessa_id'], ['commesse.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_reservations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_reservations_commessa_id'), ['commessa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_reservations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_reservations_material_id'), ['material_id'], unique=False)

    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unita_misura', sa.String(length=10), server_default='pz', nullable=False))
        batch_op.add_column(sa.Column('dimensione_2', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('quantita_prenotata', sa.Numeric(precision=18, scale=6), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('quantita_uscita', sa.Numeric(precision=18, scale=6), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_column('quantita_uscita')
        batch_op.drop_column('quantita_prenotata')
        batch_op.drop_column('dimensione_2')
        batch_op.drop_column('unita_misura')

    with op.batch_alter_table('stock_reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_reservations_material_id'))
        batch_op.drop_index(batch_op.f('ix_stock_reservations_id'))
        batch_op.drop_index(batch_op.f('ix_stock_reservations_commessa_id'))

    op.drop_table('stock_reservations')
    with op.batch_alter_table('cutting_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cutting_plans_material_id'))
        batch_op.drop_index(batch_op.f('ix_cutting_plans_id'))
        batch_op.drop_index(batch_op.f('ix_cutting_plans_commessa_id'))

    op.drop_table('cutting_plans')
    # ### end Alembic commands ###
