"""add_material_structural_fields

Revision ID: 98a6eaedc630
Revises: 363c854ca0ee
Create Date: 2026-05-23 16:28:14.701548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98a6eaedc630'
down_revision: Union[str, Sequence[str], None] = '363c854ca0ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('profilo', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('dimensioni', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('qualita', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('colata', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('commessa_ref', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('peso_u_kg', sa.Numeric(precision=12, scale=4), nullable=True))
        batch_op.add_column(sa.Column('peso_1_pz', sa.Numeric(precision=12, scale=4), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_column('peso_1_pz')
        batch_op.drop_column('peso_u_kg')
        batch_op.drop_column('commessa_ref')
        batch_op.drop_column('colata')
        batch_op.drop_column('qualita')
        batch_op.drop_column('dimensioni')
        batch_op.drop_column('profilo')
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
